services:
  app:
    build:
      context: .
    container_name: mephipracticumlottery-app
    restart: always
    depends_on:
      - db
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mephi_practicum_lottery
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: veryLongAndSecureJwtSecretKeyThatShouldBeReplacedInProduction
      JWT_EXPIRATION: 3600000
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: your-email@gmail.com
      MAIL_PASSWORD: your-app-password
      TELEGRAM_BOT_TOKEN: your-telegram-bot-token
      TELEGRAM_ADMIN_CHAT_ID: your-admin-chat-id
      ADMIN_EMAIL: admin@lottery.com

  db:
    image: postgres:17
    container_name: mephi_practicum_lottery_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mephi_practicum_lottery
    ports:
      - "5436:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: